/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('Reviews').del()
  await knex('Reviews').insert([
    {
      review_id: 1,
      product_id: 1,
      user_id: 1,
      review_text: "Top-notch quality and unbeatable convenience – the DeviceyElite laptop and phone set gets a solid 5 out of 5 stars from me.",
      review_date: "2023-09-08",
      star_rating: 5,
      first_name: "Sarah",
      last_name: "Kim",
    },
    {
      review_id: 2,
      product_id: 1,
      user_id: 2,
      review_text: "Could not be happier with the DeviceyElite laptop and phone set – a must-have for fellow entrepreneurs seeking both functionality and sophistication.",
      review_date: "2023-09-09",
      star_rating: 5,
      first_name: "Robyn",
      last_name: "Jacobs",
    },
    {
      review_id: 3,
      product_id: 1,
      user_id: 3,
      review_text: "Impressed with the DeviceyElite laptop and phone set – a powerhouse duo that keeps me productive and connected!",
      review_date: "2023-09-10",
      star_rating: 5,
      first_name: "Freddie",
      last_name: "Taylor",
    },
    {
      review_id: 4,
      product_id: 2,
      user_id: 4,
      review_text: "Solid choice for a laptop bag – the Laptoplair provides good protection, but slightly thicker padding would have earned it a full 5 stars.",
      review_date: "2023-09-07",
      star_rating: 4,
      first_name: "Nicola",
      last_name: "Lucero",
    },
    {
      review_id: 5,
      product_id: 2,
      user_id: 5,
      review_text: "The Laptoplair Laptop Bag is a perfect fit for my needs – stylish, sturdy, and offers excellent laptop protection.",
      review_date: "2023-09-09",
      star_rating: 5,
      first_name: "Levi",
      last_name: "Walter",
    },
    {
      review_id: 6,
      product_id: 2,
      user_id: 6,
      review_text: "The Laptoplair Laptop Bag offers great functionality and ample space, though a few more organizational pockets would have made it even better.",
      review_date: "2023-09-10",
      star_rating: 4,
      first_name: "Ines",
      last_name: "Lopez",
    },
    {
      review_id: 7,
      product_id: 3,
      user_id: 7,
      review_text: "Indispensable in my entrepreneurial toolkit, the Onyapack Portable Phone Charger is truly remarkable.",
      review_date: "2023-09-09",
      star_rating: 5,
      first_name: "Macy",
      last_name: "Cabrera",
    },
    {
      review_id: 8,
      product_id: 3,
      user_id: 8,
      review_text: "The Onyapack Portable Phone Charger is a lifesaver, keeping my devices powered all day long!",
      review_date: "2023-09-10",
      star_rating: 5,
      first_name: "Felix",
      last_name: "Mendez",
    },
    {
      review_id: 9,
      product_id: 4,
      user_id: 9,
      review_text: "The Endurobyte 1TB External Hard Drive is a storage powerhouse that exceeded my expectations – a definite 5-star investment.",
      review_date: "2023-09-10",
      star_rating: 5,
      first_name: "Jerome",
      last_name: "Finley",
    },
    {
      review_id: 10,
      product_id: 4,
      user_id: 10,
      review_text: "The Endurobyte 1TB External Hard Drive delivers on its promise of ample storage and seamless data transfer, earning a solid 5 stars.",
      review_date: "2023-09-11",
      star_rating: 5,
      first_name: "Tommy-Lee",
      last_name: "Harris",
    },
    {
      review_id: 11,
      product_id: 4,
      user_id: 11,
      review_text: "I am beyond impressed with the Endurobyte 1TB External Hard Drive – it is sleek, reliable, and an essential addition to my tech setup.",
      review_date: "2023-09-12",
      star_rating: 5,
      first_name: "Aadam",
      last_name: "King",
    },
    {
      review_id: 12,
      product_id: 5,
      user_id: 12,
      review_text: "Great noise cancellation and comfortable fit, though the controls on the ArmorAudio headphones could be more intuitive.",
      review_date: "2023-09-10",
      star_rating: 4,
      first_name: "Kaya",
      last_name: "Terry",
    },
    {
      review_id: 13,
      product_id: 6,
      user_id: 13,
      review_text: "Absolutely love the IvoryMarker Whiteboard – it is a game-changer for organizing my ideas and tasks, earning a well-deserved 5 stars.",
      review_date: "2023-09-07",
      star_rating: 5,
      first_name: "Chad",
      last_name: "Rollins",
    },
    {
      review_id: 14,
      product_id: 6,
      user_id: 14,
      review_text: "Could not be happier with the IvoryMarker Whiteboard – it is sleek, easy to clean, and enhances my productivity.",
      review_date: "2023-09-10",
      star_rating: 5,
      first_name: "Tanya",
      last_name: "Beasley",
    },
    {
      review_id: 15,
      product_id: 6,
      user_id: 15,
      review_text: "The IvoryMarker Whiteboard is an exceptional tool with smooth writing, making it a perfect addition to my workspace.",
      review_date: "2023-09-11",
      star_rating: 5,
      first_name: "Ellis",
      last_name: "Joyce",
    },
    {
      review_id: 16,
      product_id: 7,
      user_id: 16,
      review_text: "Love the effectiveness and style of the IlumiVue Blue Light Glasses – they are a must-have for long hours in front of screens.",
      review_date: "2023-09-09",
      star_rating: 5,
      first_name: "Francis",
      last_name: "Webster",
    },
    {
      review_id: 17,
      product_id: 7,
      user_id: 17,
      review_text: "These glasses help alleviate digital eye fatigue, though I would appreciate more style options for the IlumiVue Blue Light Glasses.",
      review_date: "2023-09-09",
      star_rating: 4,
      first_name: "Liberty",
      last_name: "Sanford",
    },
    {
      review_id: 18,
      product_id: 7,
      user_id: 18,
      review_text: "The IlumiVue Blue Light Glasses are effective at reducing eye strain, but the fit could be slightly more comfortable.",
      review_date: "2023-09-12",
      star_rating: 4,
      first_name: "Jaden",
      last_name: "Kemp",
    },
  ]);
};
